# Generated by Django 3.1.1 on 2020-10-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='img-avatar2.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
