# Generated by Django 3.1.1 on 2020-10-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201017_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetail',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
