# Generated by Django 3.1.1 on 2020-10-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_shippingdetail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetail',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
